#!/bin/bash
# Title: Plotting
# Description: Plot Change Detection results raw

python - << EOF
import matplotlib.pyplot as plt
import numpy as np
import pickle
import os

if __name__ == "__main__":
    results_dir = "${BASH_ARGV[1]}"
    with open(f'{results_dir}/artifact.pkl', 'rb') as f:
        data = pickle.load(f)

    markers = [
        'x', 's', 'd', 'v', '^', '<', '>', 'p', 'h',
        'H', 'D', '8', 'P', 'X', 'o', 'x', 's', 'd', 'v',
        '^', '<', '>', 'p', 'h', 'H', 'D', '8', 'P', 'X'
    ]
    n_batches_list = [x for x  in data['results_raw'][0] if type(x) == int]
    ICRB_A = lambda n: (config.a**2-1)/(config.b*config.n_samples*n)
    ICRB_B = lambda n: (config.b**2-1)/(config.a*config.n_samples*n)
    ICRB_tau = lambda n: config.n_samples/(n*config.a*config.b)
    for element, icrb in zip(['A', 'B', 'tau'], [ICRB_A, ICRB_B, ICRB_tau]):
        plt.figure()
        plt.title(f'MSE for {element}')
        plt.xlabel(r'$\delta^2$')
        plt.ylabel(r'$n_{\mathrm{batches}}$')


        for i, results_dict in enumerate(data['results'].items()):
            for j, estimator in enumerate(results_dict):
                plt.loglog(
                    n_batches_list,
                    results_dict[estimator][element],
                    label=f'{estimator}',
                    marker=markers[Z*i+j],
                    linestyle='None'
                )
        # ICRB
        icrb_element = icrb(np.array(n_batches_list))
        plt.loglog(
            n_batches_list,
            icrb_element,
            label=f'ICRB',
            marker='o',
            linestyle='-'
        )
        plt.legend()
    plt.show()
EOF
